### ISSUE TITLE
Exception thrown when trying to open the bottom sheet

### ISSUE THREAD

**Issue by Eel2000** [DanKyungu/OverSheet#1]
Hello @DanKyungu .
I encountered an exception when I was working with the library. I've installed the lib and I create a simple button that had a click event. the click event calls the `Application.Current.MainPage.ShowBottomSheet(new DetailsPage(),cornerRadius:10,false);`
the **DetailsPages** is a simple MauiContentPage with a label. but its  throws this exception
**Java.Lang.IllegalArgumentException: 'The view is not a child of CoordinatorLayout**. How can I solve this issue

**Comment by DanKyungu** [comment]
Your DetailsPage is a ContentPage or a ContentView ?

**Comment by Eel2000** [comment]
It's a contentPage
But i think that i get what's going on
I didn't use **ContentView** I used **ContentPage** instead

**Comment by Eel2000** [comment]
Maybe it will be good to specify it in the readme

**Comment by Eel2000** [comment]
I don't know why but i still get the same exception even with the ContentView
My call
![image](https://user-images.githubusercontent.com/44249870/187705042-51f8bf0f-f4dd-4824-b27b-b2485a513b07.png)

the contenView
![image](https://user-images.githubusercontent.com/44249870/187705099-0facb087-176e-4ab2-b0b9-6e60871cbaff.png)

**Comment by DanKyungu** [comment]
Can you share your sample project? 
Normally on Android the Standard BottomSheetDialog need to be contained in a ConstraintLayout contrary to the Modal BottomSheet

**Comment by Eel2000** [comment]
how to proceed??

**Comment by Eel2000** [comment]
Here is the sample https://github.com/Eel2000/MauiAppBottomSheet

**Comment by Eel2000** [comment]
Should I update the library??
