### ISSUE TITLE
Oversheet crashes while in Release Mode

### ISSUE THREAD

**Issue by kannanrs** [DanKyungu/OverSheet#10]
Maui app in debug mode with OverSheet works just fine but crashes in Release Mode... Please help me with correcting this...

TIA

Kannan

**Comment by Eel2000** [comment]
can you describe the error please

**Comment by kannanrs** [comment]
Hi..

Created a toolkit:Popup and called Application.Current.MainPage.ShowPopup(new EditItemPopup(param1, param2, param3));
which works well during Debug but crashes after a Release build..

Regards

**Comment by kannanrs** [comment]
Also the sample searches for G:\Pictures\OverSheet.png in the LIB directory...

Regards

**Comment by Eel2000** [comment]
Hi. Did you download the package from the project package manager??

**Comment by Eel2000** [comment]
it's just the package icon. G:\Pictures\OverSheet.png
please try to download the package from Nuget package manage in your project to add ref.

**Comment by kannanrs** [comment]
Hi.. Got it... couple of Styles were missing from the previous resources.. moved to app.xaml...
Thank you for a great product....

Regards

**Comment by DanKyungu** [comment]
Nice to see that this issue has been resolved.
